name: e_com
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_stripe: ^5.1.0
  get: 4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^5.4.2
  http: ^0.13.5
  image_picker: ^0.8.6
  location: ^4.4.0
  # razorpay_flutter: ^1.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/watches.json
